repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.222'
    hooks:
      - id: ruff
        args: ["--force-exclude"]

  - repo: local
    hooks:
      - id: black
        name: black
        stages: [commit]
        language: system
        entry: poetry run black --config pyproject.toml
        types: [python]

      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: poetry run isort --settings-path pyproject.toml
        types: [python]

      # - id: mypy
      #   name: mypy
      #   stages: [commit]
      #   language: system
      #   entry: poetry run mypy --config-file pyproject.toml
      #   types: [python]

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: poetry run pytest
        types: [python]
        pass_filenames: false

      - id: pytest-cov
        name: pytest
        stages: [push]
        language: system
        entry: poetry run pytest --cov ruts --cov-fail-under 85
        types: [python]
        pass_filenames: false