default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^mkdocs\.yml$
      - id: check-toml
      - id: check-added-large-files
        exclude: ^ruts/datasets/data/
      - id: check-merge-conflict

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        args: [--keep-output, --keep-count, --extra-keys, metadata.language_info.version]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.12
    hooks:
      - id: uv-lock

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        language: system
        entry: uv run ruff check --force-exclude --fix
        types_or: [python, pyi, jupyter]
        require_serial: true

      - id: ruff-format
        name: ruff format
        language: system
        entry: uv run ruff format --force-exclude
        types_or: [python, pyi, jupyter, markdown]
        require_serial: true

      - id: mypy
        name: mypy
        language: system
        entry: uv run mypy
        types: [python]
        pass_filenames: false

      - id: pytest
        name: pytest
        stages: [pre-push]
        language: system
        entry: uv run pytest -m "not network" --cov ruts
        pass_filenames: false
        always_run: true
