name: build

on:
  pull_request:
    branches:
      - "**"

env:
  TEST_PYPI_LOGIN: ${{ secrets.TEST_PYPI_LOGIN }}
  TEST_PYPI_PASS: ${{ secrets.TEST_PYPI_PASS }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install poetry
        run: |
          pip install -U pip
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
          python -m nltk.downloader punkt stopwords
      - name: Run tests
        run: |
          poetry run pytest --cov ruts --cov-fail-under 90
      - name: Send report
        run: |
          codecov
      - name: Build distribution
        if: github.event_name == "push" && startsWith(github.ref, "refs/tags")
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config http-basic.testpypi '$TEST_PYPI_LOGIN' '$TEST_PYPI_PASS'
          poetry build -f sdist
          poetry build -f wheel
          poetry publish -r testpypi
