name: build

on:
  push:
    tags:
      - "*"
  release:
    types: [published]

env:
  TEST_PYPI_LOGIN: ${{ secrets.TEST_PYPI_LOGIN }}
  TEST_PYPI_PASS: ${{ secrets.TEST_PYPI_PASS }}
  PYPI_LOGIN: ${{ secrets.PYPI_LOGIN }}
  PYPI_PASS: ${{ secrets.PYPI_PASS }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install poetry
        run: |
          pip install -U pip
          pip install poetry
      - name: Build distribution
        run: |
          poetry build -f sdist
          poetry build -f wheel
      - name: Publish distribution (test)
        if: github.event_name == 'push'
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config http-basic.testpypi $TEST_PYPI_LOGIN $TEST_PYPI_PASS
          poetry publish -r testpypi
      - name: Publish distribution
        if: github.event_name == 'release'
        run: |
          poetry config repositories.pypi https://pypi.org
          poetry config http-basic.pypi $PYPI_LOGIN $PYPI_PASS
          poetry publish -r pypi
